---
services:
  umami:
    build: .
    image: pulsebit:latest
    container_name: pulsebit
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://pulsebit:pulsebit@db:5432/pulsebit
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string # Change this in production!
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: pulsebit
      POSTGRES_USER: pulsebit
      POSTGRES_PASSWORD: pulsebit
    volumes:
      - pulsebit-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pulsebit-db-data:
